site_name: Sneaky Package Documentation
repo_name: AmateursLeague/sneaky-package
repo_url: https://github.com/AmateursLeague/sneaky-package

theme:
  name: dracula
  
include_sidebar: true
user_color_mode_toggle: true

plugin:

nav:
  - Home: index.md
  - Getting Started: usage.md
  - Installation Guide: installation.md
  - Contributing Guidelines: contributing.md

markdown_extensions:
  - toc
  - tables

extra:
  termynal:
      title: "shell"
      buttons: "macos"
      prompt_literal_start:
        - "$"
        - ">"
        - ">>>"