site_name: Sneaky Package
repo_name: AmateursLeague/sneaky-package
repo_url: https://github.com/AmateursLeague/sneaky-package

theme:
  name: material
  favicon: assets/package.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky


  
include_sidebar: true
user_color_mode_toggle: false

plugin:
  - search

nav:
  - Home: index.md
  - How it Works: how-it-works.md
  - Development Guidelines: development-guidelines.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

markdown_extensions:
  - toc
  - tables
  - pymdownx.superfences
  - pymdownx.highlight

extends: mkdocs

hljs_style: rainbow