name: Feature Test Cases

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install pytest
      run: |
        python -m pip install pytest
    
    - name: Run pytest
      run: |
        pytest --maxfail=1 --disable-warnings
